### PR TITLE
Merge pull request #2 from pricelinelabs/master

### PR DESCRIPTION
**Pull request by aganesh9**
Changed sample code

### CODE REVIEW

**Comment by chrisrng** [comment]
Theres no files changed

**Comment by aganesh9** [comment]
Can we still merge it and republish? I self-merged the changes from the previous PR

**Comment by chrisrng** [comment]
Yeah publishing to npm doesn't need a PR will contact you offline

**Comment by chrisrng** [comment]
Released 1.0.2 - https://www.npmjs.com/package/api-sheriff

**Pull request closed without merging**
